apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
spec:
  containers:
    - name: db-noticias-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      # Importa as variáves de configuração uma a uma.
      # env:
        # - name: "MYSQL_ROOT_PASSWORD"
        #   value: "q1w2e3r4"
        # - name: "MYSQL_DATABASE"     
        #  value: "empresa"
        # - name: "MYSQL_PASSWORD"
        #  value: "q1w2e3r4"
      # Importa todas as variáveis de configuração de uma vez só.  
      envFrom:
        - configMapRef: 
            name: db-configmap  
